# To run only MySQL database: docker-compose up -d
# To run both MySQL database and the app: docker-compose --profile with-app up -d



services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: store_api
    ports:
      - "3307:3306"
    volumes:
      # Mount local initialization scripts to MySQL container's entrypoint directory
      # This allows SQL scripts in ./docker/mysql/docker-entrypoint-initdb.d/ to be
      # automatically executed when the MySQL container starts up for database initialization
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  app:
    profiles:
      - with-app
    build: .
    env_file:
      - .env
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
    ports:
      - "8080:8080"
    depends_on:
      - mysql
