# Spring Boot supports both application.yaml and application.properties for configuration.
#   - application.yaml takes precedence over application.properties for overlapping properties.
#   - Properties unique to application.properties will still be loaded if not present in application.yaml.
spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3307/store_api?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    show-sql: true  # Show SQL statements in the console for debugging
    hibernate:
      ddl-auto: validate  # Only validate the database schema with entity; do not create, update, or drop tables. Fails if schema mismatches entities.
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # Use MySQL-specific SQL dialect
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 600
    refreshTokenExpiration: 864000
stripe:
  enabled: true
  timeout: 1000
  apiUrl: https://api.stripe.com
  supportedCurrencies:
    - USD
    - EUR
    - GBP
notification:
  gateway: sms
email:
    smtp:
        hostUrl: https://smtp.example.com
        port: 587
