# Spring Boot supports both application.yaml and application.properties for configuration.
#   - application.yaml takes precedence over application.properties for overlapping properties.
#   - Properties unique to application.properties will still be loaded if not present in application.yaml.

# The active profile is set to 'dev' below.
# This causes Spring Boot to load properties from 'application-dev.yaml'.
# Properties in 'application-dev.yaml' override the properties in this file.
# For example, 'spring.application.name' will be 'store-dev' from the dev profile,
# not 'store' as defined here.
spring:
  profiles:
    active: dev
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3307/store_api?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    show-sql: true  # Show SQL statements in the console for debugging
    hibernate:
      ddl-auto: validate  # Only validate the database schema with entity; do not create, update, or drop tables. Fails if schema mismatches entities.
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # Use MySQL-specific SQL dialect
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 600
    refreshTokenExpiration: 864000
stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecret: ${STRIPE_WEBHOOK_SECRET}
  enabled: true
  timeout: 1000
  apiUrl: https://api.stripe.com
  supportedCurrencies:
    - USD
    - EUR
    - GBP
notification:
  gateway: sms
email:
  smtp:
    hostUrl: https://smtp.example.com
    port: 587

# Actuator configuration to expose application info including version
management:
  info:
    build:
      enabled: true
    env:
      enabled: true
  endpoint:
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,health

# Application info that will be shown in actuator/info endpoint
info:
  app:
    name: '@project.name@'
    version: '@project.version@'
    description: '@project.description@'
    groupId: '@project.groupId@'
    artifactId: '@project.artifactId@'
